services:

  postgres:
    image: postgres:16
    container_name: mailwatch-postgres
    environment:
      POSTGRES_USER: mailwatch
      POSTGRES_PASSWORD: mailwatch
      POSTGRES_DB: mailwatch
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d:ro


volumes:
  postgres_data:
